# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time

from PyQt5.QtWidgets import QMainWindow, QApplication, QAbstractItemView


class Ui_MainWindow(QMainWindow):
    def __init__(self, master=None):
        QMainWindow.__init__(self, master)
        self.centralwidget = QtWidgets.QWidget()
        self.listWidget = QtWidgets.QListWidget(self)
        self.listWidget.setGeometry(QtCore.QRect(300, 130, 256, 192))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.current_option=0
        self.listWidget.setStyleSheet("selection-background-color: rgb(195, 225, 225);")
        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Anglais"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "French"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Chinois"))

    def wheelEvent(self, event):
        print("detected")
        self.start_time = time.time()
        self.current_option += 1
        print(self.current_option)
        self.listWidget.item(self.current_option%3).setSelected(True)


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    player = Ui_MainWindow()
    player.show()

    sys.exit(app.exec_())
